name: stock_portfolio
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.15.4
  collection: ^1.18.0
  equatable: ^2.0.5
  firebase_auth: ^4.17.9
  firebase_core: ^2.23.0
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  formz: ^0.6.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  meta: ^1.10.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  super_clipboard: ^0.8.4
  url_launcher: ^6.2.4
  uuid: ^4.3.3

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  firebase_auth_platform_interface: ^7.0.5
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
